### ISSUE TITLE
erroneous pipeline: no element "motiondetector"

### ISSUE THREAD

**Issue by somanath2004** [codebrainz/motiondetector#1]
Hi,

I generated the plugin from your source of motiondetector. when i went for building one small pipeline using motiondetector, i am getting below error. please have a look.

-----LOG -----

$ gst-launch-0.10 -v --gst-plugin-path=/usr/local/lib/gstreamer-0.10 autovideosrc ! video/x-raw-rgb ! motiondetector draw_motion=true rate_limit=500 ! ffmpegcolorspace ! queue ! autovideosink

(gst-plugin-scanner:9356): GStreamer-WARNING **: Failed to load plugin '/usr/local/lib/gstreamer-0.10/libgstmotiondetector.so': /usr/local/lib/gstreamer-0.10/libgstmotiondetector.so: undefined symbol: cvResize
WARNING: erroneous pipeline: no element "motiondetector"

----LOG Ends -----

PS : i have openCV 2.4.2 installed. its working fine with opencv sample programs.

Please guide me in correct direction so that i can able to resolve this error.

Thanks.

**Comment by codebrainz** [comment]
Someone else had this issue and they found out that the opencv.pc file is broken in 2.4.2. They never reported back what they did to get it working, so I'm not sure. You could try older or newer versions or fix the opencv.pc file. OpenCV 2.3.1 works fine here.

**Comment by somanath2004** [comment]
thanks for your comment. I have tried on 2.4.2 in order to resolve this. but i dint get any success. finally i installed 2.3.1. Its working absolutely fine and detecting motion smoothly. very thanks for your great work you have done.

I have one query and the description is given below

The video output is very slow while its detecting motion and its throwing warnings -- here is the log 

--- log --- 
There may be a timestamping problem, or this computer is too slow.
WARNING: from element /GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0/GstXvImageSink:autovideosink0-actual-sink-xvimage: A lot of buffers are being dropped.
Additional debug info:
gstbasesink.c(2875): gst_base_sink_is_too_late (): /GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0/GstXvImageSink:autovideosink0-actual-sink-xvimage: 
--- end log---

Is there any attributes/caps need to set or unset on this motiondetector element in order to improve the video display ? please let me know if u have face any such performance issue (like computer too slow or video output is playing slowly while its detecting motion) while running this below pipeline - 

$ gst-launch-0.10 -v --gst-plugin-path=/usr/local/lib/gstreamer-0.10 autovideosrc ! video/x-raw-rgb ! motiondetector draw_motion=true rate_limit=500 ! ffmpegcolorspace ! queue ! autovideosink

Thanks.

**Comment by codebrainz** [comment]
The motion detection is pretty slow IIRC so you might want to do it on another part of the pipeline (and/or turn down the resolution). Something like this maybe:

```
cam -> queue -> preview elements
    |-> queue -> motion detection elements
```

I remember there was also some "sync" property available which sometimes helped with performance.

Good luck
